# CircleCI configuration file

version: 2.1
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout

      - run:
        command: echo Hello World.

      - run:
        command: date