version: 2.1

jobs:
  hello-job:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - run: sudo apt install clang
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: clang -Wall -o build/main.out src/main.c


workflows:
  my-workflow:
    jobs:
      - hello-job